# Generated by Django 5.2.14 on 2026-05-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140, verbose_name='ho ten')),
                ('phone', models.CharField(max_length=40, verbose_name='so dien thoai')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='noi dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngay gui')),
                ('is_read', models.BooleanField(default=False, verbose_name='da doc')),
            ],
            options={
                'verbose_name': 'lien he khach gui',
                'verbose_name_plural': 'lien he khach gui',
                'ordering': ['-created_at'],
            },
        ),
    ]
