# Generated by Django 5.2.14 on 2026-05-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='tieu de')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='mo ta ngan')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='anh banner')),
                ('button_text', models.CharField(blank=True, max_length=80, verbose_name='chu nut')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='duong dan nut')),
                ('is_active', models.BooleanField(default=True, verbose_name='hien thi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='thu tu')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AutoParts', max_length=160, verbose_name='ten website')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='logo')),
                ('hotline', models.CharField(blank=True, max_length=40, verbose_name='hotline')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dia chi')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('zalo_url', models.URLField(blank=True, verbose_name='Zalo')),
                ('google_map_iframe', models.TextField(blank=True, verbose_name='Google Maps iframe')),
            ],
            options={
                'verbose_name': 'cau hinh website',
                'verbose_name_plural': 'cau hinh website',
            },
        ),
    ]
