# Generated by Django 5.2.14 on 2026-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'cấu hình website', 'verbose_name_plural': 'cấu hình website'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='chữ nút'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='đường dẫn nút'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/', verbose_name='ảnh banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='hiển thị'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='thứ tự'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='mô tả ngắn'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=180, verbose_name='tiêu đề'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='địa chỉ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='AutoParts', max_length=160, verbose_name='tên website'),
        ),
    ]
