# Generated by Django 5.2.14 on 2026-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_options_alter_banner_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='slogan',
            field=models.CharField(blank=True, default='Phụ tùng chính hãng - Đồng hành mọi hành trình', max_length=180, verbose_name='slogan'),
        ),
    ]
