# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='hero button text'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_button_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='hero button URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='hero description'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='hero banner image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='hero title'),
        ),
    ]
