# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_hero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=120, verbose_name='hero eyebrow'),
        ),
    ]
