# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_hero_eyebrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_button_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='chữ nút banner'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_button_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='đường dẫn nút banner'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='mô tả banner'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=120, verbose_name='dòng giới thiệu nhỏ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='ảnh banner trang chủ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='tiêu đề banner'),
        ),
    ]
