# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sitesetting_hero_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=120, verbose_name='dòng giới thiệu nhỏ'),
        ),
    ]
