# Generated by Django 5.2.14 on 2026-06-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banner_eyebrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_button_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_eyebrow',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_title',
        ),
    ]
