# Generated by Django 5.2.14 on 2026-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sitesetting_hero_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
