# Generated by Django 5.2.14 on 2026-06-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_business_url',
            field=models.URLField(blank=True, verbose_name='Google Business Profile'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO description mac dinh'),
        ),
    ]
