# Generated by Django 5.2.14 on 2026-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesetting_google_business_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='x_url',
            field=models.URLField(blank=True, verbose_name='X/Twitter'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
