# Generated by Django 5.2.14 on 2026-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesetting_instagram_url_sitesetting_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Google Analytics Measurement ID'),
        ),
    ]
