# Generated by Django 5.2.14 on 2026-06-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesetting_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180, verbose_name='SEO title trang chu'),
        ),
    ]
