# Generated by Django 5.2.14 on 2026-06-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesetting_seo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
