# Generated by Django 5.2.14 on 2026-05-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gioi thieu cong ty', max_length=180, verbose_name='tieu de')),
                ('content', models.TextField(verbose_name='noi dung')),
                ('image', models.ImageField(blank=True, upload_to='pages/', verbose_name='anh')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')),
            ],
            options={
                'verbose_name': 'trang gioi thieu',
                'verbose_name_plural': 'trang gioi thieu',
            },
        ),
    ]
