# Generated by Django 5.2.14 on 2026-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'trang giới thiệu', 'verbose_name_plural': 'trang giới thiệu'},
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=models.TextField(verbose_name='nội dung'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/', verbose_name='ảnh'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='Giới thiệu công ty', max_length=180, verbose_name='tiêu đề'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='cập nhật lúc'),
        ),
    ]
