# Generated by Django 5.2.14 on 2026-05-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_aboutpage_options_alter_aboutpage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Khuyến mãi', max_length=180, verbose_name='tiêu đề')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('image', models.ImageField(blank=True, upload_to='pages/promotions/', verbose_name='ảnh')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lúc')),
            ],
            options={
                'verbose_name': 'trang khuyến mãi',
                'verbose_name_plural': 'trang khuyến mãi',
            },
        ),
    ]
