# Generated by Django 5.2.14 on 2026-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_promotionpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='mô tả ngắn')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('image', models.ImageField(blank=True, upload_to='promotions/', verbose_name='ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='hiển thị')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
            ],
            options={
                'verbose_name': 'bài khuyến mãi',
                'verbose_name_plural': 'bài khuyến mãi',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
