# Generated by Django 5.2.14 on 2026-05-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='ten danh muc')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='anh/icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='hien thi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='thu tu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='danh muc cha')),
            ],
            options={
                'verbose_name': 'danh muc',
                'verbose_name_plural': 'danh muc',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='ten san pham')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('sku', models.CharField(max_length=80, unique=True, verbose_name='ma san pham/SKU')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='anh san pham')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='gia')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='gia khuyen mai')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='rating')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='mo ta ngan')),
                ('description', models.TextField(blank=True, verbose_name='mo ta')),
                ('is_featured', models.BooleanField(default=False, verbose_name='san pham noi bat')),
                ('is_active', models.BooleanField(default=True, verbose_name='hien thi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ngay cap nhat')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='danh muc')),
            ],
            options={
                'verbose_name': 'san pham',
                'verbose_name_plural': 'san pham',
                'ordering': ['-created_at'],
            },
        ),
    ]
