# Generated by Django 5.2.14 on 2026-06-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='ảnh sản phẩm')),
                ('alt_text', models.CharField(blank=True, max_length=180, verbose_name='mô tả ảnh')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product', verbose_name='sản phẩm')),
            ],
            options={
                'verbose_name': 'ảnh sản phẩm',
                'verbose_name_plural': 'ảnh sản phẩm',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
